name: Telegram Web Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
      max-parallel: 4

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ghcr.io/techlover1/tweb

      - name: Log in to the container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
